# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Austin/Documents/CEC330_3/Final_from_example/Final_from_example.cache/wt [current_project]
set_property parent.project_path C:/Users/Austin/Documents/CEC330_3/Final_from_example/Final_from_example.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Austin/Documents/CEC330_3/Final_from_example/Final_from_example.srcs/sources_1/new/SPI_If.vhd
  C:/Users/Austin/Documents/CEC330_3/Final_from_example/Final_from_example.srcs/sources_1/new/ADXL362Ctrl.vhd
  C:/Users/Austin/Documents/CEC330_3/Final_from_example/Final_from_example.srcs/sources_1/new/AccelArithmetics.vhd
  C:/Users/Austin/Documents/CEC330_3/Final_from_example/Final_from_example.srcs/sources_1/new/AccelerometerCtl.vhd
  C:/Users/Austin/Documents/CEC330_3/Final_from_example/Final_from_example.srcs/sources_1/new/Top.vhd
}
read_xdc C:/Users/Austin/Documents/CEC330_3/Final_from_example/Final_from_example.srcs/constrs_1/new/Master.xdc
set_property used_in_implementation false [get_files C:/Users/Austin/Documents/CEC330_3/Final_from_example/Final_from_example.srcs/constrs_1/new/Master.xdc]

synth_design -top Top -part xc7a100tcsg324-1
write_checkpoint -noxdef Top.dcp
catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
