# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/CEC330/ClockTest/ClockTest.cache/wt [current_project]
set_property parent.project_path F:/CEC330/ClockTest/ClockTest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib F:/CEC330/ClockTest/ClockTest.srcs/sources_1/new/top.vhd
read_xdc F:/CEC330/ClockTest/ClockTest.srcs/constrs_1/new/master.xdc
set_property used_in_implementation false [get_files F:/CEC330/ClockTest/ClockTest.srcs/constrs_1/new/master.xdc]

synth_design -top Divider -part xc7a100tcsg324-1
write_checkpoint -noxdef Divider.dcp
catch { report_utilization -file Divider_utilization_synth.rpt -pb Divider_utilization_synth.pb }
