# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/CEC330/PWM_test/PWM_test.cache/wt [current_project]
set_property parent.project_path F:/CEC330/PWM_test/PWM_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib F:/CEC330/PWM_test/PWM_test.srcs/sources_1/new/PWM.vhd
read_xdc F:/CEC330/PWM_test/PWM_test.srcs/constrs_1/new/master.xdc
set_property used_in_implementation false [get_files F:/CEC330/PWM_test/PWM_test.srcs/constrs_1/new/master.xdc]

synth_design -top PWM -part xc7a100tcsg324-1
write_checkpoint -noxdef PWM.dcp
catch { report_utilization -file PWM_utilization_synth.rpt -pb PWM_utilization_synth.pb }
