# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Austin/Documents/CEC330/Lab_6/Lab_6.cache/wt [current_project]
set_property parent.project_path C:/Users/Austin/Documents/CEC330/Lab_6/Lab_6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Austin/Documents/CEC330/Lab_6/Lab_6.srcs/sources_1/new/Seven_seg_driver.vhd
  C:/Users/Austin/Documents/CEC330/Lab_6/Lab_6.srcs/sources_1/new/PWM.vhd
  C:/Users/Austin/Documents/CEC330/Lab_6/Lab_6.srcs/sources_1/new/Divider.vhd
  C:/Users/Austin/Documents/CEC330/Lab_6/Lab_6.srcs/sources_1/new/Binary_to_decimal.vhd
  C:/Users/Austin/Documents/CEC330/Lab_6/Lab_6.srcs/sources_1/new/Top_countdown.vhd
}
read_xdc C:/Users/Austin/Documents/CEC330/Lab_6/Lab_6.srcs/constrs_1/new/Lab_6_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Austin/Documents/CEC330/Lab_6/Lab_6.srcs/constrs_1/new/Lab_6_constraints.xdc]

synth_design -top Top_countdown -part xc7a100tcsg324-1
write_checkpoint -noxdef Top_countdown.dcp
catch { report_utilization -file Top_countdown_utilization_synth.rpt -pb Top_countdown_utilization_synth.pb }
